### ISSUE TITLE
Using lawgs in a lamda function

### ISSUE THREAD

**Issue by matthewchung74** [mentum/lawgs#3]
Lawgs is awesome. It really simplifies writing to cloudwatch. I have a question I was hoping to get your 2 cents on. I have a lamda function which receives logging requests from mobile clients. The only way I could get the event to write out is by putting a timer before context.succeed() Do you know a cleaner way to approach this?

```
var lawgs = require('lawgs');
var logger  = lawgs.getOrCreate('/betatest/ios/logs/ble');
logger.config({
    // Shows the debugging messages
    showDebugLogs: true, /* Default to false */
    // Change the frequency of log upload, regardless of the batch size
    uploadMaxTimer: 0, /* Defaults to 5000ms */
    // Max batch size. An upload will be triggered if this limit is reached within the max upload time
    uploadBatchSize: 1 /* Defaults to 500 */
});

exports.handler = function(event, context) {
    logger.log('events', event);
    setTimeout(function() {
        context.succeed("cool beans 1");
    }, 2000);
};
```

**Comment by slvnperron** [comment]
Thanks @foobar8675 I really appreciate your feedback!

Events are missing in lawgs, but would be very simple to add to the library. What you need is to hook on `logger.on('uploaded')`. This event should be added [here](https://github.com/mentum/lawgs/blob/master/index.js#L82).

If you can't make this change I can do it later this week for you!

**Comment by slvnperron** [comment]
Just to be clear, your code would look like this:

``` js
var lawgs = require('lawgs');
var logger  = lawgs.getOrCreate('/betatest/ios/logs/ble');
logger.config({
    // Shows the debugging messages
    showDebugLogs: true, /* Default to false */
    // Change the frequency of log upload, regardless of the batch size
    uploadMaxTimer: 0, /* Defaults to 5000ms */
    // Max batch size. An upload will be triggered if this limit is reached within the max upload time
    uploadBatchSize: 1 /* Defaults to 500 */
});

exports.handler = function(event, context) {
    logger.log('events', event);
    logger.on('uploaded', function() {
        context.succeed("cool beans 1");
    });
};
```

**Comment by matthewchung74** [comment]
Excellent and thank you. I'm going to do a bit more testing and submitting a PR later today.
