### ISSUE TITLE
Why you are not using DescribeLogStreams

### ISSUE THREAD

**Issue by Moussawi7** [mentum/lawgs#5]
Hi,
In your code, i can see that you are getting the next sequence token from exception !!.
Why you are not using **_DescribeLogStreams**_(http://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_DescribeLogStreams.html) at startup .
Thank you.

``` javascript
cw.putLogEvents(params, function(err, data) {
            if (err) {
                if(err.code ===  DATA_ACCEPTED || err.code === INVALID_TOKEN) {
                    var nextToken = err.message.split(': ')[1];
                    _log('Getting sequence token', nextToken);
                    deferred.resolve(_uploadLogs(group, stream, logs, nextToken));
                } else {
                    console.error(err);
                    deferred.reject(err);
                }
            }
            else deferred.resolve(data);
        });
```

**Comment by slvnperron** [comment]
hi! the reason why I get the next sequence token from the exception is to handle concurrency issues (i.e. your app might not be the only app logging to that stream or you might have many instances of this app running). 

I am actually already calling DescribeLogStreams at the beginning so if you are willing to contribute you can pick the token from there :) (see https://github.com/mentum/lawgs/blob/master/index.js#L189)

**Comment by Moussawi7** [comment]
Hi,
Thank you for your clarification, and sorry for bothering you.
